---
title: "The Power of Efficiency"
format: html
editor: visual
---

As we’ve said in the class efficiency is a pivotal component of statistical computing (and data science). In this essay, give an explanation of what that term “efficiency” means in relation to statistical computing and describe some places where you encountered efficiency and understood its importance. Your essay should address the following questions:

-   What is the definition of “efficiency”?

-   What does efficiency look like in statistical computing / data science?

-   What does efficiency allow you to do?

-   Why is efficiency important?

-   Where did you encounter efficiency, and what were some [“a-ha” moments](https://www.merriam-webster.com/dictionary/aha%20moment) you had about efficiency? (For the latter, tie each a-ha moment to an artifact in the portfolio.)

To me, efficiency means properly allocating time to achieve the most net value out of time. In statistical computing and data science, efficiency is to ensure readability and practicality of your code in a concise and cohesive manner. This is extremely critical since it reduces the burden of the reviwer auditing ones code in a professional setting or the compiler running code in a timely manner. Efficiency enables me to leverage every minute of the day to effectively allocate time towards course work, physical activity/health, mental health, and consuking optimal nutrition. It invokes my critical thinking when tackling redundancey both in my personal life and school to automate unnecessary tasks. When programming, I always embark on techniques such as joins() to best connect data sets in the simplest way possible and outputting a lean and clean data frame for audience to indulge when reviewing. This was highlighted both in my lab 5 and my SQL course when leveraging nested queries in "where" and "from" clauses.

I remember encountering astonishing efficiency at my dentist who leverages a digital system that only requires your initials and phone to check-in with a 5 minute waiting time till being taken in. This may be analogous to developing a vectorised function that only has a .0005 seconds of compiling time!
